AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  AuthFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/handlers/authHandler.handler
      Runtime: nodejs18.x  # Update this to the latest version
      CodeUri: .
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBUri
          JWT_SECRET: !Ref JwtSecret
Outputs:
  AuthFunction:
    Description: "Authentication Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
Parameters:
  MongoDBUri:
    Type: String
    Default: "YOUR_MONGODB_ATLAS_CONNECTION_STRING"
  JwtSecret:
    Type: String
    Default: "YOUR_SECRET_KEY"
