AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  AuthFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/handlers/authHandler.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          MONGODB_URI: !Sub '{{resolve:secretsmanager:mongodb-uri-new:SecretString}}'
          JWT_SECRET: !Ref JwtSecret
      Events:
        AuthApi:
          Type: Api
          Properties:
            Path: /auth
            Method: post
Outputs:
  AuthFunction:
    Description: "Authentication Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
Parameters:
  JwtSecret:
    Type: String
    Default: "YOUR_SECRET_KEY"
